# air.toml

# Set the path to your main Go file
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  # cmd = "echo 'Precompile...' && pnpm run build &&  go build -o ./tmp/main cmd/main.go"
  cmd = "go build -o ./tmp/main cmd/main.go"
  delay = 1000
[log]
  level = "debug"
[color]
  app = ""
  build = "white"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
